# ワークフロー名
name: api_vibraition_collection
on:
  schedule:
    # 定期実行する時間・・・①
    - cron: ',15,25,35,45,55 * * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール・・・②
          pip install requests
          pip install pandas
          pip install numpy

      - name: Run script
        run: |
          # 定期実行するファイルを指定。・・・③
          python api_vibraition_collection.py
